// Conditional defines:
//
// GEx: use GraphicEx Library to support many graphic formats
// GIF: use RX Library to support GIF format
// TNT: use Tnt Unicode Controls (useful under Windows 2000/XP)
//
// Note:
// These defines are commented by default so the component can be compiled
// without any additional libraries. Uncomment defines below if you have
// required libraries installed.

// {$define GEx}
// {$define GIF}
// {$define TNT}
